version: '3.9'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=JaverDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - mynetwork

  api-java:
    image: banco-javer:1.0.0
    hostname: api-java
    networks:
      - mynetwork
    depends_on:
      - db

  api-gateway:
    image: banco-javer-gateway:1.0.0
    hostname: api-gateway-java
    ports:
      - "8080:8080"
    networks:
      -

volumes:
  postgres-db:

networks:
  mynetwork: